version: '3.8'
services:
  etsin-search-rabbitmq:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-search-rabbitmq
      configs:
        - source: etsin-qvain-app-config-dev
          target: /home/etsin-user/app_config
      ports:
        - "5673:5673"
        - "15673:15673"
      volumes:
        - ../etsin-finder-search/etsin_finder_search/:/etsin_finder_search/
configs:
  etsin-qvain-app-config-dev:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True