version: '3.8'
services:
  etsin-search-rabbitmq-consumer:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-search-rabbitmq-consumer
      configs:
        - source: etsin-qvain-app-config
          target: /home/etsin-user/app_config
      ports:
        - "5673:5673"
        - "15673:15673"
      extra_hosts:
        - "metax.fd-dev.csc.fi:172.17.0.1"
      volumes:
        - ../etsin-finder-search/etsin_finder_search/:/etsin_finder_search/
      depends_on:
        - fairdata-nginx
configs:
  etsin-qvain-app-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True
