version: '3'
services:
  elasticsearch:
    hostname: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      elastic-network:
        aliases:
          - alias1
  #rabbitmq:
   # image: etsin-search-rabbitmq
   # depends_on:
   #   - elasticsearch
volumes:
  esdata:
    driver: local
networks:
  elastic-network:
    external: true
